### PR TITLE
update linkgrammar version in pom.xml

### PR DESCRIPTION
**Pull request by noskill**
update pom.xml to use any version higher than was specified

### CODE REVIEW

**Comment by noskill** [comment]
@linas @ngeiswei

**Comment by linas** [comment]
what are you using relex for?

**Comment by noskill** [comment]
We are using relex to convert questions to atomese queries in our visual question answering demo. It currently supports only two question types, we haven't tried yet using relex2logic since we need first to implement joint learning of neural network models and truth values in atomspace ontology.  
More about this project here https://github.com/singnet/semantic-vision/tree/master/experiments/opencog/question2atomese and here https://github.com/singnet/semantic-vision/tree/master/experiments/opencog/pattern_matcher_vqa

There is docker container for this code https://hub.docker.com/r/opencog/vqa

**Comment by linas** [comment]
OK. Just be aware that ... relex is a low-quality data filter.  For beginners, the relex outputs are "easy to understand", and thus are very appealing, because they seem so simple and obvious and nice to use. However, once you gain some experience with it, you will learn that it is a data-damager. It takes an OK parse from link-grammar, and then damages it, lowering it's quality.  It is NOT a good long-term building block.

Again: for certain simple, basic applications, it works well enough. It's easy-to-use. So keep using it for now. Just be aware that it's a data filter that blurs and distorts data. Like a blur filter for an image: the output is fuzzier, less sharp, and sometimes just wrong.

**Pull request merged**
